### PR TITLE
Update file_contexts

### PR DESCRIPTION
**Pull request by umerov1999**

### CODE REVIEW

**Comment by neobuddy89** [comment]
vendor and system/vendor are symlinked. Do you get any error without this?

**Comment by umerov1999** [comment]
> vendor and system/vendor are symlinked. Do you get any error without this?

My phone is bootloped, and i have error in logcat - "sepolicy denied exec power_hal 1.3 service."
I change to (vendor|system/vendor), and this became normal

**Comment by umerov1999** [comment]
Тут проблема в том, что походу сервис вызывается по пути /system/vendor, а туда sepolicy не даёт разрешение

**Comment by neobuddy89** [comment]
Full log please.

**Pull request closed without merging**
